import Head from "next/head";
import React from "react";
import { reduxWrapper } from "../redux/store";
import { useSelector } from "react-redux";
import { setUsers } from "../redux/usersSlice";

const Users = () => {
  const users = useSelector((state) => state.usersSlice.users);

  return (
    <div>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-5 grid grid-cols-6 gap-6">
        {users.map((user, key) => {
          return (
            <div
              key={key}
              className="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700"
            >
              <a href="#">
                <img className="rounded-t-lg w-full" src={user.avatar} alt="" />
              </a>
              <div className="p-5">
                <a href="#">
                  <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    {user.first_name} {user.last_name}
                  </h5>
                </a>
                <p className="mb-3 font-normal text-gray-700 dark:text-gray-400 text-justify">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat....
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export const getServerSideProps = reduxWrapper.getServerSideProps(
  (store) => async () => {
    const response = await fetch("https://reqres.in/api/users");
    const res = await response.json();
    store.dispatch(setUsers(res));
  }
);

export default Users;
